#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/scim-bridge-el

# Written by Jim Van Zandt <jrv@debian.org>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=scim-bridge-el

case $FLAVOR in
    emacs|emacs21|emacs20|emacs19|mule2|*xemacs*)
    exit 0
    ;;
    *)
    EMACSEN=$FLAVOR
    ;;
esac

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

#FLAVORTEST=`echo $FLAVOR | cut -c-6`
#if [ ${FLAVORTEST} = xemacs ] ; then
#    SITEFLAG="-no-site-file"
#else
#    SITEFLAG="--no-site-file"
#fi
#FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"
FLAGS="-no-site-file -q -batch -l path.el -f batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

cd "$ELDIR"
LINKS=`echo *.el`
cd l10n
LINKS2=`echo *.el`

if [ ! -d "$ELCDIR" ]; then
    mkdir "$ELCDIR"
    chmod 755 "$ELCDIR"
fi
if [ ! -d "$ELCDIR/l10n" ]; then
    mkdir "$ELCDIR/l10n"
    chmod 755 "$ELCDIR/l10n"
fi

cd "$ELCDIR"

TOELDIR=../../../emacs/site-lisp/$PACKAGE
TOELDIR2=../$TOELDIR/l10n

rm -f *.el path.el
for f in $LINKS; do
    ln -sf "$TOELDIR/$f" ./
done
FILES=`/bin/ls -1 *.el`
cat << EOF > path.el
(setq load-path (cons "." load-path))
(setq byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${FILES}
chmod 644 *.elc
rm -f path.el

if [ -d l10n ]; then
    cd l10n
    rm -f *.elc __path.el
    for f in $LINKS2; do
	ln -sf "$TOELDIR2/$f" ./
    done
    FILES=`/bin/ls -1 *.el`
    cat << EOF > path.el
(setq load-path (cons ".." load-path))
(setq load-path (cons "." load-path))
(setq byte-compile-warnings nil)
EOF
    ${FLAVOR} ${FLAGS} ${FILES}
    chmod 644 *.elc
    rm -f path.el
fi

exit 0
